config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'comments/new'
  get 'comments/show'
  get 'users/index'
  # GET /about
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"  

  resources :tweets
  post "tweets/new", to: "tweets#create"
  patch "tweets/:id/edit", to: "tweets#update"
  delete "tweets/:id/edit", to: "tweets#destroy"

  resources :posts
  
  get "user/:id", to: "users#show", as: :user
  post "posts/new", to: "posts#create"
  root to: "main#index"

  resources :posts do
    resources :comments, only: [:create]
  end
  
  post '/posts/:id/like', to: 'posts#like', as: 'like_post'
  #delete '/posts/:id/unlike', to: 'posts#unlike', as: 'unlike_post'

  resources :users do
    member do
      delete :delete_post
    end
  end

  resources :comments
  post "posts/:id", to: "comments#create"
  
  get "post/:id", to: "posts#show"
  
  delete 'users/:id' => 'users#destroy', as: :destroy_user
  
  post 'user/:id/promote', to: 'users#promote_to_vip', as: :promote_to_vip_user
  post 'user/:id/demote', to: 'users#demote_from_vip', as: :demote_from_vip_user

  get 'vip', to: 'vip#index', as: 'vip'
  
  post '/user/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
  delete '/user/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe_user'
  
  get "user/:id/edit", to: "users#edit", as: :user_edit
  patch "user/:id/edit", to: "users#update"
  
  get "post/:id/edit", to: "posts#edit"
  patch "post/:id/edit", to: "posts#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :body, presence: true, length: { minimum: 1, maximum: 200 }

    def published?
        comment_id?
    end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/new_tweet.rb
class NewTweet < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    validates :body, length: { minimum: 1, maximum: 600 }
    # validates :avatar, presence: true
    def published?
        new_tweet_id?
    end
end

app/models/newtweet.rb
class Newtweet < ApplicationRecord
    
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    #mount_uploader :photo, PhotoUploader
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    validates :body, length: { minimum: 1, maximum: 600 }

    def photo=(input_data)
        self.photo_data = input_data.read
      end
    
      def photo
        photo_data.blank? ? nil : StringIO.new(photo_data)
    end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8

class User < ApplicationRecord
    before_create :set_default_vip_status
    #mount_uploader :avatar, AvatarUploader
    has_many :tweets
    has_one_attached :avatar
    has_many :likes
    has_many :posts
    has_secure_password
    has_many :subscribers
    
    def avatar=(input_data)
        self.avatar_data = input_data.read
      end
    
      def avatar
        StringIO.new(avatar_data)
    end
    
    def set_default_vip_status
      self.vip ||= false
    end

    validates :email, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :avatar, presence: true
    
end

app/controllers/tweets_controller.rb
# encoding: utf-8
class TweetsController < ApplicationController
    before_action :require_user_logged_in!
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]
    def new
        @newtweet = NewTweet.new
        @newtweet.user = Current.user
    end

    def index
        @newtweets = NewTweet.all
        @users = User.all
    end

    def create 
        @newtweet = NewTweet.new(tweet_params)
        if @newtweet.save
            redirect_to tweets_path, notice: 'Пост успешно опубликован.'
        else
            render :new
        end
    end

    def edit
    end

    def update
        @newtweet.update(tweet_params)
        redirect_to tweets_path, notice: 'Пост успешно изменён.'
    end

    def destroy
        @newtweet.destroy
        redirect_to tweets_path, notice: 'Пост успешно удалён.'
    end

    private
    def tweet_params
        params.require(:new_tweet).permit(:user, :body, :avatar,)
    end

    def set_tweet
        @newtweet = NewTweet.find(params[:id])
    end
end

app/controllers/vip_controller.rb
class VipController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vip_helper.rb
module VipHelper
end

app/views/tweets/_form.html.erb
<h1>Добавить занятие</h1>


<%= form_with model: @newtweet, url: new_tweet_path, data: {turbo: false} do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        <strong>Опубликовано от</strong>
        <%= form.label :user, "#{Current.user.email}" %>
        <input readonly type="hidden" <%= form.text_field :user, :value => Current.user.email, class: 'form-control'%>
        <hr>
        <%= form.text_field :body, class: 'form-control' %><br>
        <div class="mt-3">
            <%= form.submit 'Confim', class: 'btn btn-primary' %>
        </div>
     </div>
      
<% end %>

app/views/tweets/_tweets.html.erb
<% @newtweets.order(created_at: :desc).each do |tweet|%>
<div class="mb-3 card card-body tweet-box">
    <div class="mb-3">
        <div class="mb-2">
        <% @users.each do |user| %>
            <% if tweet.user == user.email %>
                <%# image_tag user.avatar_url, class: 'avatar' %>
                <%= image_tag "data:avatar/jpeg;base64,#{Base64.encode64(user.avatar.read)}", class: 'avatar' %>
                <strong class = 'tweet-user'>
                    <%= link_to "#{tweet.user}", "/user/#{user.id}"%>
                    <% if user.vip? %>
                        <span class="VIP-p">ПРЕП</span>
                    <% elsif Current.user.email. == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
                        <span class="VIP-p">ADMIN</span>
                    <% end %>
                </strong>
            <% end %>
        <% end %>
        </div>
        <br>
        <p class="tweet-body"><%= tweet.body %></p>
        <% if tweet.user == Current.user.email || Current.user.email == 'dorogino@gmail.com' || Current.user.email == 'amigo2542@gmail.com' %>
            <%= link_to "Изменить занятие", edit_tweet_path(tweet) %>
        <% end %>
        <%# button_to 'Записаться на занятие', class: 'btn btn-mrimary' %>
        <style>
          .btnA {
            margin-left: 3px;
          }
        </style>

        <button class="btn btn-primary btnA", style="">Записаться на занятие</button>
    </div>
</div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Изменение поста</h1>


<%= form_with model: @newtweet, url: edit_tweet_path, data: {turbo: false} do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        
        
        <input readonly type="hidden" <%= form.text_field :user, :value => @newtweet.user, class: 'form-control'%>
        <hr>
        <%= form.text_field :body, class: 'form-control' %><br>
        <div class="mt-3">
            <%= form.submit 'Confim', class: 'btn btn-primary' %>
            
        </div>
     </div>
      
<% end %>
<% if Current.user.email == @newtweet.user || Current.user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
    <%= button_to "Delete", edit_tweet_path(@newtweet), method: :delete, title: 'Удалить вопрос', class: 'btn btn-danger' %>
<% end %>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
    <h1>Занятия</h1>
    <% if Current.user.vip? || Current.user.email = 'dorogino@gmail.com' || Current.user.email = 'amigo2542@gmail.com' %>
        <%= link_to 'Добавить занятие', new_tweet_path, class: 'btn btn-primary' %>
    <% end %>
</div>

<div class="mb3">
<%= render 'tweets' %>
</div>

app/views/tweets/new.html.erb
<h1>Добавить занятие</h1>

<%= form_with model: @newtweet, url: new_tweet_path, :html => { :multipart => true }, data: {turbo: false} do |form| %>
    <%= render "shared/form_errors", form: form %>
    <div class="mb-3">
        <strong>Опубликованно от:</strong>
        <%= form.label :user, "#{Current.user.email}" %>
        <input readonly type="hidden" <%= form.text_field :user, :value => Current.user.email, class: 'form-control'%>
        <hr>
        <%= form.text_field :body, class: 'form-control' %><br>
        <div class="mt-3">
            <%= form.submit 'Принять', class: 'btn btn-primary' %>
        </div>
     </div>
<% end %>