config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'comments/new'
  get 'comments/show'
  get 'users/index'
  # GET /about
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"  

  resources :tweets
  post "tweets/new", to: "tweets#create"
  patch "tweets/:id/edit", to: "tweets#update"
  delete "tweets/:id/edit", to: "tweets#destroy"

  resources :posts
  
  get "user/:id", to: "users#show", as: :user
  post "posts/new", to: "posts#create"
  root to: "main#index"

  resources :posts do
    resources :comments, only: [:create]
  end
  
  post '/posts/:id/like', to: 'posts#like', as: 'like_post'
  #delete '/posts/:id/unlike', to: 'posts#unlike', as: 'unlike_post'

  resources :users do
    member do
      delete :delete_post
    end
  end

  resources :comments
  post "posts/:id", to: "comments#create"
  
  get "post/:id", to: "posts#show"
  
  delete 'users/:id' => 'users#destroy', as: :destroy_user
  
  post 'user/:id/promote', to: 'users#promote_to_vip', as: :promote_to_vip_user
  post 'user/:id/demote', to: 'users#demote_from_vip', as: :demote_from_vip_user

  get 'vip', to: 'vip#index', as: 'vip'
  
  post '/user/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
  delete '/user/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe_user'
  
  get "user/:id/edit", to: "users#edit", as: :user_edit
  patch "user/:id/edit", to: "users#update"
  
  get "post/:id/edit", to: "posts#edit"
  patch "post/:id/edit", to: "posts#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :body, presence: true, length: { minimum: 1, maximum: 200 }

    def published?
        comment_id?
    end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/new_tweet.rb
class NewTweet < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    validates :body, length: { minimum: 1, maximum: 600 }
    # validates :avatar, presence: true
    def published?
        new_tweet_id?
    end
end

app/models/newtweet.rb
class Newtweet < ApplicationRecord
    
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    #mount_uploader :photo, PhotoUploader
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    validates :body, length: { minimum: 1, maximum: 600 }

    def photo=(input_data)
        self.photo_data = input_data.read
      end
    
      def photo
        photo_data.blank? ? nil : StringIO.new(photo_data)
    end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8

class User < ApplicationRecord
    before_create :set_default_vip_status
    #mount_uploader :avatar, AvatarUploader
    has_many :tweets
    has_one_attached :avatar
    has_many :likes
    has_many :posts
    has_secure_password
    has_many :subscribers
    
    def avatar=(input_data)
        self.avatar_data = input_data.read
      end
    
      def avatar
        StringIO.new(avatar_data)
    end
    
    def set_default_vip_status
      self.vip ||= false
    end

    validates :email, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :avatar, presence: true
    
end

app/controllers/vip_controller.rb
class VipController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def abbreviated_number(number)
    return number.to_s if number.nil?
    if number >= 1_000_000
      "#{(number / 1_000_000.0).round(1)}млн"
    elsif number >= 1_000
      "#{(number / 1_000.0).round(1)}к"
    else
      number.to_s
    end
  end

  def abbreviated_likes_count(post)
    likes_count = post.likes_count || 0
    if likes_count >= 1_000_000
      "#{(likes_count / 1_000_000.0).round(1)}млн"
    elsif likes_count >= 1_000
      "#{(likes_count / 1_000.0).round(1)}к"
    else
      likes_count.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vip_helper.rb
module VipHelper
end

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :post_id, style: "display: block" %>
    <%= form.number_field :post_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/_like.html.erb
<div id="<%= dom_id like %>">
  <p>
    <strong>User:</strong>
    <%= like.user_id %>
  </p>

  <p>
    <strong>Post:</strong>
    <%= like.post_id %>
  </p>

</div>

app/views/likes/edit.html.erb
<h1>Editing like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Show this like", @like %> |
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Likes</h1>

<div id="likes">
  <% @likes.each do |like| %>
    <%= render like %>
    <p>
      <%= link_to "Show this like", like %>
    </p>
  <% end %>
</div>

<%= link_to "New like", new_like_path %>

app/views/likes/new.html.erb
<h1>New like</h1>

<%= render "form", like: @like %>

<br>

<div>
  <%= link_to "Back to likes", likes_path %>
</div>

app/views/likes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @like %>

<div>
  <%= link_to "Edit this like", edit_like_path(@like) %> |
  <%= link_to "Back to likes", likes_path %>

  <%= button_to "Destroy this like", @like, method: :delete %>
</div>