config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'comments/new'
  get 'comments/show'
  get 'users/index'
  # GET /about
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"  

  resources :tweets
  post "tweets/new", to: "tweets#create"
  patch "tweets/:id/edit", to: "tweets#update"
  delete "tweets/:id/edit", to: "tweets#destroy"

  resources :posts
  
  get "user/:id", to: "users#show", as: :user
  post "posts/new", to: "posts#create"
  root to: "main#index"

  resources :posts do
    resources :comments, only: [:create]
  end
  
  post '/posts/:id/like', to: 'posts#like', as: 'like_post'
  #delete '/posts/:id/unlike', to: 'posts#unlike', as: 'unlike_post'

  resources :users do
    member do
      delete :delete_post
    end
  end

  resources :comments
  post "posts/:id", to: "comments#create"
  
  get "post/:id", to: "posts#show"
  
  delete 'users/:id' => 'users#destroy', as: :destroy_user
  
  post 'user/:id/promote', to: 'users#promote_to_vip', as: :promote_to_vip_user
  post 'user/:id/demote', to: 'users#demote_from_vip', as: :demote_from_vip_user

  get 'vip', to: 'vip#index', as: 'vip'
  
  post '/user/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
  delete '/user/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe_user'
  
  get "user/:id/edit", to: "users#edit", as: :user_edit
  patch "user/:id/edit", to: "users#update"
  
  get "post/:id/edit", to: "posts#edit"
  patch "post/:id/edit", to: "posts#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :body, presence: true, length: { minimum: 1, maximum: 200 }

    def published?
        comment_id?
    end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/new_tweet.rb
class NewTweet < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    validates :body, length: { minimum: 1, maximum: 600 }
    # validates :avatar, presence: true
    def published?
        new_tweet_id?
    end
end

app/models/newtweet.rb
class Newtweet < ApplicationRecord
    
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    #mount_uploader :photo, PhotoUploader
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    validates :body, length: { minimum: 1, maximum: 600 }

    def photo=(input_data)
        self.photo_data = input_data.read
      end
    
      def photo
        photo_data.blank? ? nil : StringIO.new(photo_data)
    end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8

class User < ApplicationRecord
    before_create :set_default_vip_status
    #mount_uploader :avatar, AvatarUploader
    has_many :tweets
    has_one_attached :avatar
    has_many :likes
    has_many :posts
    has_secure_password
    has_many :subscribers
    
    def avatar=(input_data)
        self.avatar_data = input_data.read
      end
    
      def avatar
        StringIO.new(avatar_data)
    end
    
    def set_default_vip_status
      self.vip ||= false
    end

    validates :email, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :avatar, presence: true
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in!
  def index
    @user = User.find_by(params[:id])
  end

  def delete_post
    @user = User.find(params[:id])
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to @user, notice: "Пост удалён успешно."
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def show
    @comments = Comment.all
    @comments_count = @comments.size
    @posts = Post.all
    @user = User.find(params[:id])
  end
  
  def subscribe
    @user = User.find(params[:id])
    Current.user.subscribers.create(user_id: Current.user.id, user_id2: @user.id)
    @user.increment!(:subscribers_count)
    redirect_to request.referrer
  end

  def unsubscribe
    @user = User.find(params[:id])
    Current.user.subscribers.find_by(user_id2: @user.id).destroy
    @user.decrement!(:subscribers_count)
    redirect_to request.referrer
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path, notice: 'Ваш аккаунт удалён.'
  end

  def promote_to_vip
    @user = User.find(params[:id])
    @user.update(vip: true)
    redirect_to @user
  end
  
  def demote_from_vip
    @user = User.find(params[:id])
    @user.update(vip: false)
    redirect_to @user
  end

  private

    def user_params
        params.require(:user).permit(:subscribers_count, :user_id)
    end
end

app/controllers/vip_controller.rb
class VipController < ApplicationController
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def abbreviated_number(number)
    return number.to_s if number.nil?
    if number >= 1_000_000
      "#{(number / 1_000_000.0).round(1)}млн"
    elsif number >= 1_000
      "#{(number / 1_000.0).round(1)}к"
    else
      number.to_s
    end
  end

  def abbreviated_likes_count(post)
    likes_count = post.likes_count || 0
    if likes_count >= 1_000_000
      "#{(likes_count / 1_000_000.0).round(1)}млн"
    elsif likes_count >= 1_000
      "#{(likes_count / 1_000.0).round(1)}к"
    else
      likes_count.to_s
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vip_helper.rb
module VipHelper
end

app/views/users/edit.html.erb
<h1>Редактировать пользователя</h1>

<%= form_with model: @user, url: "/user/#{@user.id}/edit", :html => { :multipart => true }, data: {turbo: false} do |form| %>

    <div class="mb-3">
        <%= form.label :subscribers_count %>
        <%= form.text_field :subscribers_count, class: 'form-control', value: @user.subscribers_count %>
    </div>

    <div class="mb-3">
        <%= form.submit "Обновить", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/users/index.html.erb
<h1>My page1</h1>

app/views/users/show.html.erb
 <div class = "wall-box mx-auto">
    <div class="mt-4 mb-2 ProfileHeader">
        <%# image_tag @user.avatar_url, class: 'profile-avatar' %>
        <%= image_tag "data:avatar/jpeg;base64,#{Base64.encode64(@user.avatar.read)}", class: 'profile-avatar' %>
        <h1 class="profile-email">
            <%= @user.email %>
            <% if @user.vip? %>
                <span class="VIP-p">ПРЕП</span>
            <% elsif @user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
                <span class="VIP-p">ADMIN</span>
            <% end %>
        </h1>
        <% if @user.id == Current.user.id %>
          <div class="edit-button">
            <%= link_to fa_icon('edit'), password_path %>
          </div>
        <% end %>
        <% if Current.user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %> 
            <%= link_to fa_icon('bars'), edit_user_path, class: 'admin-btn' %>
        <% end %>
        <hr class="hr">
    </div>
    <div class="ProfileHeader">
        <% if @user.id == Current.user.id %>
            <%= link_to 'Добавить пост', new_post_path, class: 'btn btn-info' %>
        <% else %>
            <% if Current.user.subscribers.exists?(user_id2: @user.id) %>
                <%= button_to 'Отписаться', unsubscribe_user_path(@user), method: :delete, class: 'btn btn-danger unsubub-btn' %>
            <% else %>
                <%= button_to 'Подписаться', subscribe_user_path(@user), method: :post, class: 'btn btn-info sub-btn' %>
            <% end %>
        <% end %>  
    <div>
        <span class="subscribe-count">Подписчики: <%= abbreviated_number(@user.subscribers_count) %></span> 
    </div>
    <% if Current.user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
        <% if @user.vip? %>    
                <%= button_to "Убрать ПРЕП", demote_from_vip_user_path(@user), method: :post, class: 'btn btn-danger'%>  
        <% else %>
                <%= button_to "Добавить ПРЕП", promote_to_vip_user_path(@user), method: :post, class: 'btn btn-warning'%>
        <% end %>
    <% end %>
    </div>
    <% @posts.each do |post| %>
        <% if post.user == @user.email %>
        <div class="ProfileHeader">
            <div class="_post_content">
                <div class="PostHeader">
                    <div>
                        <% if post.user == @user.email %>
                            <%# image_tag @user.avatar_url, class: 'Avatar' %>
                        <%= image_tag "data:avatar/jpeg;base64,#{Base64.encode64(@user.avatar.read)}", class: 'Avatar' %>
                        <% end %>
                    </div>
                    <div class="PostHeaderInfo">
                        <% if post.user == @user.email %>
                            <h5>
                                <span><%= @user.email %></span>
                                <% if @user.vip? %>
                                    <span class="VIP-p">ПРЕП</span>
                                <% elsif  @user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
                                    <span class="VIP-p">ADMIN</span>
                                <% end %>
                            </h5>
                        <% end %>
                    </div>
                </div>
                <div class="content">
                    <div class="post_info">
                        <div class="wall_text">
                            <%= post.body %>
                        </div>
                        <div class="PhotoOnPost">
                            <% if post.photo.present? %>
                                <%= image_tag "data:photo/jpeg;base64,#{Base64.encode64(post.photo.read)}", class: 'img-fluid' %>
                            <% end %>
                        </div>
                        <div class="btn_wrap">
                            <div class="btns">
                                <div class="like-button"> 
                                    <%= button_to fa_icon("heart"), like_post_path(post), method: :post, class: 'item-button' %>
                                    <span class="like_count"><%= abbreviated_likes_count(post) %></span> 
                                    <% if Current.user.likes.exists?(post: @post) %>
                                        <%= button_to fa_icon("heart-o"), like_post_path(post), method: :post, class: 'item-button' %>
                                    <% end %>                                                     
                                    <script>
                                        //location.reload();
                                    </script>   
                                </div>
                                <div class="comment-button">
                                    <%= link_to fa_icon('comment'), "/post/#{post.id}" %>                      
                                    <span class="comments-count"><%= post.comments.count %></span>
                                </div>
                                <div class="share-button">
                                    <button class="fa-solid fa-share fa-lg"></button>
                                    <span class="share-count">0</span>
                                </div>
                                <% if Current.user.email == post.user || Current.user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
                                    <div class="trash-button remove-styles">
                                        <%= button_to fa_icon("trash"), delete_post_user_path(post), method: :delete, class: 'item-button' %>
                                    </div>
                                <% end %>
                                <% if Current.user.email == 'dorogino@gmail.com' || @user.email == 'amigo2542@gmail.com' %>
                                    <div class="cog-button remove-styles">
                                        <%= link_to fa_icon("cog"), edit_post_path(post), method: :delete, class: 'item-button' %>
                                    </div>
                                <% end %>
                            </div>                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    <% end %>
</div>