config/routes.rb
Rails.application.routes.draw do
  resources :likes
  get 'comments/new'
  get 'comments/show'
  get 'users/index'
  # GET /about
  get "about", to: "about#index"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
  
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"  

  resources :tweets
  post "tweets/new", to: "tweets#create"
  patch "tweets/:id/edit", to: "tweets#update"
  delete "tweets/:id/edit", to: "tweets#destroy"

  resources :posts
  
  get "user/:id", to: "users#show", as: :user
  post "posts/new", to: "posts#create"
  root to: "main#index"

  resources :posts do
    resources :comments, only: [:create]
  end
  
  post '/posts/:id/like', to: 'posts#like', as: 'like_post'
  #delete '/posts/:id/unlike', to: 'posts#unlike', as: 'unlike_post'

  resources :users do
    member do
      delete :delete_post
    end
  end

  resources :comments
  post "posts/:id", to: "comments#create"
  
  get "post/:id", to: "posts#show"
  
  delete 'users/:id' => 'users#destroy', as: :destroy_user
  
  post 'user/:id/promote', to: 'users#promote_to_vip', as: :promote_to_vip_user
  post 'user/:id/demote', to: 'users#demote_from_vip', as: :demote_from_vip_user

  get 'vip', to: 'vip#index', as: 'vip'
  
  post '/user/:id/subscribe', to: 'users#subscribe', as: 'subscribe_user'
  delete '/user/:id/unsubscribe', to: 'users#unsubscribe', as: 'unsubscribe_user'
  
  get "user/:id/edit", to: "users#edit", as: :user_edit
  patch "user/:id/edit", to: "users#update"
  
  get "post/:id/edit", to: "posts#edit"
  patch "post/:id/edit", to: "posts#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    validates :body, presence: true, length: { minimum: 1, maximum: 200 }

    def published?
        comment_id?
    end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/new_tweet.rb
class NewTweet < ApplicationRecord
    mount_uploader :avatar, AvatarUploader
    validates :body, length: { minimum: 1, maximum: 600 }
    # validates :avatar, presence: true
    def published?
        new_tweet_id?
    end
end

app/models/newtweet.rb
class Newtweet < ApplicationRecord
    
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    #mount_uploader :photo, PhotoUploader
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    validates :body, length: { minimum: 1, maximum: 600 }

    def photo=(input_data)
        self.photo_data = input_data.read
      end
    
      def photo
        photo_data.blank? ? nil : StringIO.new(photo_data)
    end
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# encoding: utf-8

class User < ApplicationRecord
    before_create :set_default_vip_status
    #mount_uploader :avatar, AvatarUploader
    has_many :tweets
    has_one_attached :avatar
    has_many :likes
    has_many :posts
    has_secure_password
    has_many :subscribers
    
    def avatar=(input_data)
        self.avatar_data = input_data.read
      end
    
      def avatar
        StringIO.new(avatar_data)
    end
    
    def set_default_vip_status
      self.vip ||= false
    end

    validates :email, presence: true, uniqueness: true, length: { maximum: 20 }
    validates :avatar, presence: true
    
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vip_helper.rb
module VipHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f823af6fe2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css" integrity="sha384-QYIZto+st3yW+o8+5OHfT6S482Zsvz2WfOzpFSXMF9zqeLcFV0/wlZpMtyFcZALm" crossorigin="anonymous">
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-tUvtJtA4f6Z1L3X3Eq2HFIosMn6ZJ3rRH3v3iqF4nThDrh8L+536B6bpJef/5Rv0lXGAQPZZW4yE8rOcTx+ow==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'apple-touch-icon.png', size: "180x180" %>
    <%= favicon_link_tag 'favicon-32x32.png', size: "32x32" %>
    <%= favicon_link_tag 'favicon-16x16.png', size: "16x16" %>
    <%= favicon_link_tag 'site.webmanifest' %>
<!--     <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest"> -->
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    
    <div class="container">
      <%= render partial: "shared/flash" %>
      <button onclick="scrollToTop()" id="scrollUpButton">Наверх</button>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <%= javascript_include_tag('updatepage.js') %>
    <%= javascript_include_tag('count.js') %>
    <%= javascript_include_tag('scrollUp.js') %>
  </body>

</html>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_form_errors.html.erb
<% if form.object.errors.any? %>
    <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>
    </div>
<% end %>

app/views/shared/_likesCount.html.erb
<% @posts.each do |post| %>
<% if post.user == @user.email %>
<span class="like_count"><%= post.likes_count %></span>
<%end%>
<%end%>

app/views/shared/_navbar.html.erb
<!-- encoding: utf-8 -->
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark fixed-top">
  <div class="container-fluid">
    <%= link_to 'Twwoter', root_path, class: 'navbar-brand text' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Главная', root_path, class: 'nav-link text' %>
        </li>
        <li>
          <%= link_to "Посты", tweets_path, class: 'nav-link text' %>
        </li>
        <li class="nav-item">
          <%= link_to 'О нас', about_path, class: 'nav-link text' %>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <div class="avatar-container">
          <% if Current.user && Current.user.avatar.present? %>
            <%# image_tag Current.user.avatar_url, class: "avatar" %>
            <%= image_tag "data:avatar/jpeg;base64,#{Base64.encode64(Current.user.avatar.read)}", class: 'Avatar' %>
          <% else %>
            <%= image_tag "default_avatar.png", class: "avatar" %>
          <% end %>
        </div>
        <% if Current.user %>
          <li class="nav-item">
            <% if Current.user %>
            <%= link_to Current.user.email, user_path(Current.user), class: 'nav-link text' %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to "Выйти", logout_path, method: :delete, class: 'btn btn-outline-secondary text' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Зарегистрироваться", sign_up_path, class: 'nav-link text' %>
          </li>
          <li class="nav-item">
            <%= link_to "Войти", sign_in_path, class: 'nav-link text' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>